# Generated by Django 4.2.5 on 2023-10-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='categorie',
            field=models.ManyToManyField(to='ticket.categorie'),
        ),
    ]
