# Generated by Django 4.2.5 on 2023-10-04 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_ticket_data_cloture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='data_cloture',
            new_name='date_cloture',
        ),
    ]
